homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 3.4444
  longitude: -76.4444
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 965
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Bogota

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:

sensor:

- platform: yr

- platform: darksky
  api_key: 095774ea272b5af8dd0c2a5986c6f7db
  monitored_conditions:
    - icon
    - temperature
    - apparent_temperature
    - humidity
    - daily_summary
    - apparent_temperature_max
    - apparent_temperature_min
    
    mqtt:
#  embedded:
    # Your HBMQTT config here. Example at:
    # http://hbmqtt.readthedocs.org/en/latest/references/broker.html#broker-configuration

switch:
- platform: mqtt
  name: "Living Room fan"
  state_topic: "stat/sonoff0/1/POWER"
  command_topic: "cmnd/sonoff0/1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Bed Room fan"
  state_topic: "stat/sonoff1/1/POWER"
  command_topic: "cmnd/sonoff1/1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

automation:
-  alias: 'Turn off bedroom fan after 1AM'
   trigger:
     platform: time
     after: '01:00:00'
   action:
     service: switch.turn_off
     entity_id:
       - switch.bed_room_fan
       
     -  alias: 'Turn off bedroom fan after 2AM'
   trigger:
     platform: time
     after: '02:00:00'
   action:
     service: switch.turn_off
     entity_id:
       - switch.bed_room_fan

-  alias: 'Turn off living fan after midnight'
   trigger:
     platform: time
     after: '00:00:00'
   action:
     service: switch.turn_off
     entity_id:
       - switch.living_room_fan
